#pragma once

#include "../core.h"

#define GBA_SCREEN_WIDTH  240
#define GBA_SCREEN_HEIGHT 160

#define GBA_CPU_FREQ          0x1000000 // 16.8 MHz
#define GBA_FRAMES_PER_SECOND 60

#define GBA_CPU_CYCLES_PER_FRAME (GBA_CPU_FREQ / GBA_FRAMES_PER_SECOND)
#define GBA_CPU_STEPS_PER_FRAME  GBA_CPU_CYCLES_PER_FRAME
